/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.4. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module blinky
    ( // Inputs
      input wire  CLOCK_50 // clock
    , input wire  KEY0 // reset

      // Outputs
    , output wire [7:0] LEDR
    );
  // Blinky.hs:37:1-7
  wire [31:0] karg;
  reg [31:0] result = 32'd0;

  assign karg = ((result >> (64'sd22)));

  assign LEDR = karg[0+:8];

  // register begin
  always @(posedge CLOCK_50 or  negedge  KEY0) begin : result_register
    if ( ! KEY0) begin
      result <= 32'd0;
    end else begin
      result <= (result + 32'd1);
    end
  end
  // register end


endmodule

