// AUTOMATICALLY GENERATED by verilambda-shim-gen. DO NOT EDIT.
// Regenerate by re-running `cabal build` in the project that
// depends on verilambda.

#ifndef VERILAMBDA_BLINKY_SHIM_H
#define VERILAMBDA_BLINKY_SHIM_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef void *VerilambdaSim;

/* Packed state of every port. Passed into step() with inputs filled
 * in; step() overwrites it with the post-eval values of every port.
 * Fields are in declaration order; this must match the user's HKD
 * record layout.
 */
typedef struct {
  uint8_t CLOCK_50;
  uint8_t KEY0;
  uint8_t LEDR;
} verilambda_blinky_state_t;

VerilambdaSim verilambda_blinky_new(void);
void verilambda_blinky_delete(VerilambdaSim sim);

/* Copy in.inputs → model, eval, copy every port → out.
 * in and out may alias. */
void verilambda_blinky_step(VerilambdaSim sim,
                            const verilambda_blinky_state_t *in,
                            verilambda_blinky_state_t *out);

void verilambda_blinky_trace_open(VerilambdaSim sim, const char *path);
void verilambda_blinky_trace_close(VerilambdaSim sim);
void verilambda_blinky_trace_dump(VerilambdaSim sim, uint64_t time);

void verilambda_blinky_final(VerilambdaSim sim);

#ifdef __cplusplus
}
#endif
#endif
