// AUTOMATICALLY GENERATED by verilambda-shim-gen. DO NOT EDIT.
// Regenerate by re-running `cabal build` in the project that
// depends on verilambda.

#include "verilambda_blinky_shim.h"
#include "Vblinky.h"
#include "verilated.h"
#include "verilated_vcd_c.h"

namespace {

struct Wrapper {
  VerilatedContext ctx;
  Vblinky *top;
  VerilatedVcdC *trace;
  uint64_t time;
  Wrapper() : top(new Vblinky(&ctx, "TOP")), trace(nullptr), time(0) {
    Verilated::traceEverOn(true);
  }
  ~Wrapper() {
    if (trace) {
      trace->close();
      delete trace;
    }
    top->final();
    delete top;
  }
};

} // namespace

extern "C" {

VerilambdaSim verilambda_blinky_new(void) {
  return static_cast<VerilambdaSim>(new Wrapper());
}

void verilambda_blinky_delete(VerilambdaSim sim) {
  delete static_cast<Wrapper *>(sim);
}

void verilambda_blinky_step(VerilambdaSim sim,
                            const verilambda_blinky_state_t *in,
                            verilambda_blinky_state_t *out) {
  auto *w = static_cast<Wrapper *>(sim);
  w->top->CLOCK_50 = in->CLOCK_50;
  w->top->KEY0 = in->KEY0;
  /* LEDR is an output — not driven from in */
  w->top->eval();
  out->CLOCK_50 = w->top->CLOCK_50;
  out->KEY0 = w->top->KEY0;
  out->LEDR = w->top->LEDR;
}

void verilambda_blinky_trace_open(VerilambdaSim sim, const char *path) {
  auto *w = static_cast<Wrapper *>(sim);
  if (w->trace)
    return;
  w->trace = new VerilatedVcdC;
  w->top->trace(w->trace, 99);
  w->trace->open(path);
}

void verilambda_blinky_trace_close(VerilambdaSim sim) {
  auto *w = static_cast<Wrapper *>(sim);
  if (!w->trace)
    return;
  w->trace->close();
  delete w->trace;
  w->trace = nullptr;
}

void verilambda_blinky_trace_dump(VerilambdaSim sim, uint64_t t) {
  auto *w = static_cast<Wrapper *>(sim);
  if (w->trace) {
    w->trace->dump(t);
  }
  w->time = t;
}

void verilambda_blinky_final(VerilambdaSim sim) {
  static_cast<Wrapper *>(sim)->top->final();
}

} // extern "C"
